replicaCount: 1

image:
  repository: overhang-backend-config
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

service:
  type: ClusterIP
  port: 8888

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

environment:
  variables:
    - name: ENV_VAR
      value: "value"