namespace: default

replicaCount: 1

image:
  repository: samjsui/overhang-backend-config
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

service:
  type: ClusterIP
  port: 8888

resources:
  requests:
    cpu: "150m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_PROFILES_ACTIVE
      value: dev