namespace: default

replicaCount: 1

image:
  repository: overhang-backend-gateway
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

service:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_CONFIG_IMPORT
      value: "overhang-backend-config"
    - name: SPRING_PROFILES_ACTIVE
      value: dev

ingress:
  enabled: true
  host: dev.overhang.trustyourfeet.com
  annotations:
    kubernetes.io/ingress.class: nginx
  spec:
    ingressClassName: nginx
  paths:
    - path: /
      pathType: Prefix
  backend:
    serviceName: overhang-backend-gateway
    servicePort: 8080