namespace: default

replicaCount: 1

image:
  repository: samjsui/overhang-backend-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

environment:
  variables:
    - name: ENV_VAR
      value: "value"

ingress:
  enabled: true
  host: dev.overhang.trustyourfeet.com
  annotations:
    kubernetes.io/ingress.class: nginx
  spec:
    ingressClassName: nginx
  paths:
    - path: /
      pathType: Prefix
  backend:
    serviceName: overhang-backend-gateway
    servicePort: 8080