namespace: default

replicaCount: 1

image:
  repository: samjsui/overhang-backend-gateway
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

service:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

ingress:
  enabled: true
  host: overhang.trustyourfeet.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  spec:
    ingressClassName: nginx
  paths:
    - path: /
      pathType: Prefix
  backend:
    serviceName: overhang-backend-gateway
    servicePort: 80

spring:
  config:
    import: http://overhang-backend-config:8888