namespace: default

replicaCount: 1

image:
  repository: samjsui/overhang-backend-gateway
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

gateway:
  name: overhang-gateway
  className: nginx

route:
  name: overhang-gateway-route
  path: /

service:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080

resources:
  requests:
    cpu: "150m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

spring:
  config:
    import: http://overhang-backend-config:8888