apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overhang-backend-gateway.fullname" . }}
  labels:
    app: {{ include "overhang-backend-gateway.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "overhang-backend-gateway.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "overhang-backend-gateway.fullname" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: {{ include "overhang-backend-gateway.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ index .Values.service.ports 0 "port" }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        {{- range .Values.environment.variables }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
