apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default "nginx" }}
  listeners:
  - protocol: HTTP
    port: 80
    name: http