apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overhang-backend-gateway-ingress
  annotations:
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        path: {{ .Values.ingress.paths.path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .Values.ingress.backend.service.name }}
            port:
              number: {{ .Values.ingress.backend.service.port }}
