apiVersion: v1
kind: Service
metadata:
  name: {{ include "overhang-backend-gateway.fullname" . }}
  labels:
    app: {{ include "overhang-backend-gateway.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values.service.ports 0 "port" }}
      targetPort: {{ index .Values.service.ports 0 "targetPort" }}
  selector:
    app: {{ include "overhang-backend-gateway.fullname" . }}
