apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values.service.ports 0 "port" }}
      targetPort: {{ index .Values.service.ports 0 "targetPort" }}
  selector:
    app: {{ .Release.Name }}
