replicaCount: 1

image:
  repository: overhang-backend-registry
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

service:
  type: ClusterIP
  port: 8761

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_CONFIG_IMPORT
      value: "http://overhang-backend-config:8888"
    - name: SPRING_PROFILES_ACTIVE
      value: dev