replicaCount: 1

image:
  repository: samjsui/overhang-backend-registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8761

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

environment:
  variables:
    - name: ENV_VAR
      value: "value"