replicaCount: 1

service:
  type: ClusterIP
  port: 9092

controller:
  initContainerResources:
    limits:
      cpu: "100m"
      memory: "256Mi"
      ephemeral-storage: "50Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
      ephemeral-storage: "50Mi"

zookeeper:
  enabled: false

replicaCount: 1

controller:
  replicaCount: 1

kafka:
  mode: kraft

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

metrics:
  kafka:
    enabled: false
