replicaCount: 1

service:
  type: ClusterIP
  port: 9092

controller:
  resourcesPreset: "nano"

zookeeper:
  enabled: false

replicaCount: 1

controller:
  replicaCount: 1

kafka:
  mode: kraft

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

metrics:
  kafka:
    enabled: false
