replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "150m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

zookeeper:
  enabled: false

externalZookeeper:
  servers:
    - zookeeper.dev.svc.cluster.local:2181

service:
  type: ClusterIP
  port: 9092

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

metrics:
  kafka:
    enabled: false
