replicaCount: 1

service:
  type: ClusterIP
  port: 9092

zookeeper:
  enabled: false

controller:
  replicaCount: 1
  resourcesPreset: "nano"

kafka:
  mode: kraft

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

metrics:
  kafka:
    enabled: false
