apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8081
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        env:
        - name: SPRING_CONFIG_IMPORT
          value: {{ .Values.spring.config.import }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrap.servers }}
        - name: DB_HOST
          value: {{ .Values.db.host }}
        - name: DB_PORT
          value: {{ .Values.db.port | quote }}
        - name: DB_NAME
          value: {{ .Values.db.name }}
        - name: DB_USERNAME
          value: {{ .Values.db.username }}
        - name: DB_PASSWORD
          value: {{ .Values.db.password }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}
              key: jwtSecret
        {{- range .Values.environment.variables }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
