namespace: default

replicaCount: 1

image:
  repository: overhang-backend-auth
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-overhang-registry

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: JWT_EXPIRATION
      value: 86400000

spring:
  config:
    import: http://overhang-backend-config:8888

auth:
  jwtSecret: ""