replicaCount: 1

image:
  namespace: samjsui
  repository: overhang-backend-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

environment:
  variables:
    - name: ENV_VAR
      value: "value"