replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/zookeeper
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "150m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 2181

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

metrics:
  enabled: false
