name: Deploy to Dev Cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_NAMESPACE: samjsui
      INGRESS_NGINX_K8S_NAMESPACE: ingress-nginx
      OVERHANG_BACKEND_CONFIG_NAME: overhang-backend-config
      OVERHANG_BACKEND_REGISTRY_NAME: overhang-backend-registry
      OVERHANG_BACKEND_AUTH_NAME: overhang-backend-auth
      OVERHANG_BACKEND_GATEWAY_NAME: overhang-backend-gateway

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig and setup Kubernetes context
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_CREDENTIALS_DEV }}
          kubectl config current-context

      - name: Determine Kubernetes namespace name
        id: determine_namespace
        run: echo "K8S_NAMESPACE=dev" >> $GITHUB_ENV

      - name: Clean up Service Namespace
        run: |
          if kubectl get namespace $K8S_NAMESPACE; then
            kubectl delete all --all -n $K8S_NAMESPACE
            kubectl delete configmaps --all -n $K8S_NAMESPACE
            kubectl delete secrets --all -n $K8S_NAMESPACE
          else
            echo "Namespace $K8S_NAMESPACE does not exist, skipping cleanup."
          fi

      - name: Create Docker Registry Secret
        run: |
          kubectl create secret docker-registry dev-overhang-registry \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email=${{ secrets.DOCKERHUB_EMAIL }} \
            -n $K8S_NAMESPACE || echo "Secret already exists"

      - name: Deploy Config Service (overhang-backend-config)
        run: |
          helm upgrade --install $OVERHANG_BACKEND_CONFIG_NAME ./charts/$OVERHANG_BACKEND_CONFIG_NAME \
            --set image.tag=latest \
            --set namespace=$K8S_NAMESPACE \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Deploy Auth Service (overhang-backend-auth)
        run: |
          helm upgrade --install $OVERHANG_BACKEND_AUTH_NAME ./charts/$OVERHANG_BACKEND_AUTH_NAME \
            --set image.tag=latest \
            --set namespace=$K8S_NAMESPACE \
            --set spring.config.import=http://overhang-backend-config.$K8S_NAMESPACE.svc.cluster.local/ \
            --set auth.jwtSecret=${{ secrets.AUTH_JWT_SECRET }} \
            --set db.host=${{ secrets.DB_HOST }} \
            --set db.port=25060 \
            --set db.name=auth_dev \
            --set db.username=${{ secrets.DB_USERNAME }} \
            --set db.password=${{ secrets.DB_PASSWORD }} \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Deploy Gateway Service (overhang-backend-gateway)
        run: |
          helm upgrade --install $OVERHANG_BACKEND_GATEWAY_NAME ./charts/$OVERHANG_BACKEND_GATEWAY_NAME \
            --set image.tag=latest \
            --set namespace=$K8S_NAMESPACE \
            --set spring.config.import=http://overhang-backend-config.$K8S_NAMESPACE.svc.cluster.local/ \
            --set ingress.host=dev.overhang.trustyourfeet.com \
            --set overhang.service.auth.url=http://overhang-backend-auth.$K8S_NAMESPACE.svc.cluster.local/ \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Verify deployments
        run: |
          kubectl get pods -n $K8S_NAMESPACE
