name: Docker Build and Push

on:
  repository_dispatch:
    types: [docker-build-push]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_NAMESPACE: samjsui

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Checkout service code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.client_payload.service_repo }}
        ref: ${{ github.event.client_payload.commit_sha }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_NAMESPACE }}/${{ github.event.client_payload.service_name }}:${{ github.event.client_payload.image_tag }}
